name: Monorepo CI

on:
  push:
    branches:
      - master

jobs:
  file_changes:
    runs-on: ubuntu-latest
    name: File Changes
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Install Depdencies'
        run: 'yarn'

      - name: 'Node TAP'
        run: cat output/example-tap.txt | yarn tap -
